# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rLkCk108OKmPvEDzYAf9x93sTDabV2AJ
"""



"""#AULA 02
##Começando com Python e OpenCV
"""

# Commented out IPython magic to ensure Python compatibility.
# Baixar a imagem e as ferramentas

!wget --no-check-certificate \
    https://raw.githubusercontent.com/maxbassoul/opencv-learning/main/foto.jpeg \
    -O foto.jpeg
!wget --no-check-certificate \
    https://raw.githubusercontent.com/maxbassoul/opencv-learning/main/common.py \
    -O common.py

# Importar o openCV

import cv2
import common
import numpy as np

# Funções para o notebook interativo
# %matplotlib inline
from matplotlib import pyplot as plt  #permite desenhar imagens no notebook
import pylab                          #manipular tamanhos 
pylab.rcParams['figure.figsize'] = (10.0, 8.0)

fotografia = cv2.imread('foto.jpeg')
plt.imshow(fotografia)

# Canais divididos 
b,g,r = cv2.split(fotografia)

# Canal R (red, vermelho) em tons de cinza 
plt.imshow(r, cmap= 'gray')

# Canal R (vermelho) 
plt.imshow( r, cmap = None)

CanaisOrdemCorreta = cv2.merge([r,g,b])
plt.imshow(CanaisOrdemCorreta)

plt.imshow(fotografia)

CanaisOrdemCorreta2 = cv2.merge([r,b,g])
plt.imshow(CanaisOrdemCorreta2)

CanaisOrdemCorreta3 = cv2.merge([g,r,b])
plt.imshow(CanaisOrdemCorreta3)

!wget --no-check-certificate \
 https://raw.githubusercontent.com/tiagoboeing/processamento-digital-de-imagens/master/src/imgs/test-ruido-nature.jpg \
    -O figuraRuido2.jpg

ruido3 = cv2.imread('figuraRuido2.jpg')
plt.imshow(ruido3)
median2 = cv2.medianBlur(ruido3,5)
plt.subplot(121),plt.imshow(ruido3),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(median2),plt.title('Mediana')
plt.xticks([]), plt.yticks([])